---
abstract: 'load Moose or Mouse or Mo'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Any::Mo
name: Any-Mo
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  Mo: 0.31
  Moose: 2.00
  Mouse: 0
requires:
  Carp: 0
  Scalar::Util: 0
  perl: 5.6.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Any-Mo
  homepage: https://metacpan.org/release/Any-Mo
  license: http://dev.perl.org/licenses/
version: 0.31
